name: YesHealth
description: Pharmachy App
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.1.0
  cached_network_image: ^3.1.0
  provider: ^6.1.1
  sembast: 3.5.0+1
  path: ^1.8.3
  intl: ^0.18.0
  intl_phone_field: ^3.2.0

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  sqlite3_flutter_libs: 0.5.18
  hexcolor: ^3.0.1
  image_picker: ^1.0.5
  money_formatter: ^0.0.5
  flutter_local_notifications: 16.3.0 
  flutter_vibrate: ^1.3.0
  simple_animations: ^5.0.2
  shimmer: ^3.0.0
  flutter_fadein: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true
  assets:
  - assets/obat.json
  - assets/test_image.png
  - assets/logo_512.png
  - assets/login_bg.png
  fonts:
    - family: DS-Digital
      fonts:
        - asset: fonts/ds-digit.ttf